function y = J(rho,theta,k,T,v0,Number)

% "J" function for Lewis (2000) vol of vol expansion

if Number==1
	y = (theta*T + (1-exp(-k*T))*(v0/k - 2*theta/k) - exp(-k*T)*(v0-theta)*T);
	y = y*rho/k;
elseif Number==3
	y = theta*T ...
	  + theta/2/k*(1-exp(-2*k*T)) ... 
	  - 2*theta/k*(1-exp(-k*T)) ...
	  + (v0-theta)*1/k*(exp(-k*T)-exp(-2*k*T)) ...
	  + (v0-theta)*(-2*exp(-k*T)*T) ...
	  + (v0-theta)*1/k*(1-exp(-k*T));
  	y = y/2/k^2;
elseif Number==4
	y = theta/k*(T*(1+exp(-k*T)) - 2/k*(1-exp(-k*T))) ...
	  + (v0-theta)/k*(1/k*(1-exp(-k*T)) - T*exp(-k*T)) ...
	  - 0.5*T^2*exp(-k*T)*(v0-theta);
    y = y*rho^2/k;
end

	
